language: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules
script:
  - npm test
  - docker build -t marcelomaia/terceirizadas_frontend .
  - docker run -d -p 8080:80 marcelomaia/terceirizadas_frontend
  - docker ps -a

deploy:
  provider: script
  script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push marcelomaia/terceirizadas_frontend
  on:
    branch: development
